# Geminya Bot Configuration
# This file provides default settings for the bot
# You can override these with environment variables

# Language setting
language: "en"

# Bot behavior
max_history_length: 7
debug: true
max_response_length: 1999

# AI Model settings (can be overridden by server-specific settings)
default_model: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free"
check_model: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free"
temperature: 0.6

# Server restrictions (empty list means no restrictions)
# Add server IDs here to restrict bot to specific servers
active_servers:
  []
  # - "1393258849867272325"
  # - "700261922259599420"

# Anime Wordle Configuration
anime_wordle:
  # Difficulty-based score weight distributions
  # Higher weights mean more likely to be selected
  # Scores are out of 100 (AniList format)
  difficulty_weights:
    easy:
      "85-100": 10    # Extremely popular/acclaimed anime (highest chance)
      "75-84": 10      # Popular anime
    
    normal:
      "80-100": 15    # Great anime
      "60-79": 15     # Good anime  
      "50-59": 2      # Below average
      "40-49": 1      # Poor anime
      "0-39": 1       # Bad anime
    
    hard:
      "80-100": 3    # Great anime (highest weight)
      "60-79": 10    # Good anime (high weight)
      "50-59": 5      # Below average (low weight)
      "40-49": 1      # Poor anime (very low weight)
      "0-39": 1       # Bad anime (minimal weight)
    
    expert:
      "80-100": 1     # Extremely rare acclaimed anime
      "70-79": 2      # Less known decent anime
      "60-69": 5      # Obscure average anime
      "50-59": 10     # Unknown below average (highest chance)
      "40-49": 10     # Obscure poor anime (very high chance)
      "0-39": 1      # Ultra obscure/bad anime (high chance)
  
  # Legacy/fallback score weights (used if difficulty_weights not found)
  # Higher weights mean more likely to be selected
  # Scores are out of 100 (AniList format)
  score_weights:
    "80-100": 15    # Great anime (highest weight)
    "60-79": 15     # Good anime (high weight)
    "50-59": 2      # Below average (low weight)
    "40-49": 1      # Poor anime (very low weight)
    "0-39": 1       # Bad anime (minimal weight)
  
  # Maximum number of pages to search through (each page = 50 anime)
  # Higher values = more anime variety but slower startup
  max_search_pages: 200
  
  # Sorting method for anime selection
  # Options: POPULARITY_DESC, SCORE_DESC, TRENDING_DESC, FAVOURITES_DESC
  # POPULARITY_DESC = Most popular/well-known anime first
  # SCORE_DESC = Highest rated anime first  
  # TRENDING_DESC = Currently trending anime first
  # FAVOURITES_DESC = Most favorited anime first
  sort_method: "POPULARITY_DESC"
