# Geminya Bot Configuration
# This file provides default settings for the bot
# You can override these with environment variables

# Language setting
language: "en"

# Bot behavior
max_history_length: 7
debug: true
max_response_length: 1999

# AI Model settings (can be overridden by server-specific settings)
default_model: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free"
check_model: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free"
temperature: 0.6

# Server restrictions (empty list means no restrictions)
# Add server IDs here to restrict bot to specific servers
active_servers:
  []
  # - "1393258849867272325"
  # - "700261922259599420"

# Anime Wordle Configuration
anime_wordle:
  # Weighted random selection based on score ranges
  # Higher weights mean more likely to be selected
  # Scores are out of 100 (AniList format)
  score_weights:
    80-100: 15    # Great anime (highest weight)
    60-79: 15     # Good anime (high weight)
    50-59: 2     # Below average (low weight)
    40-49: 1     # Poor anime (very low weight)
    0-39: 1     # Bad anime (minimal weight)
  
  # Maximum number of pages to search through (each page = 50 anime)
  # Higher values = more anime variety but slower startup
  max_search_pages: 200
  
  # Sorting method for anime selection
  # Options: POPULARITY_DESC, SCORE_DESC, TRENDING_DESC, FAVOURITES_DESC
  # POPULARITY_DESC = Most popular/well-known anime first
  # SCORE_DESC = Highest rated anime first  
  # TRENDING_DESC = Currently trending anime first
  # FAVOURITES_DESC = Most favorited anime first
  sort_method: "POPULARITY_DESC"
